Repository SRS-Project/app, pull requests merged in 2018-05, with the labels that each got.

#10 renderer.tsx setup
  .babelrc
  .compilerc
  .gitignore
  .prettierrc
  index.html
  package.json
  src/App.tsx
  src/SomeComponent.tsx
  src/main.ts
  src/renderer.tsx
  tsconfig.json
  webpack.renderer.config.js
  webpack.renderer.dev.config.js
Labels: in progress

#11 Migrate webpack config from Javascript to Typescript
  package.json
  tsconfig.json
  tslint.json
  webpack.config.base.js
  webpack.config.base.ts
  webpack.main.config.js
  webpack.main.config.ts
  webpack.renderer.config.js
  webpack.renderer.config.ts
  webpack.renderer.dev.config.js
  webpack.renderer.dev.config.ts
  yarn.lock
Labels: in progress

#28 add Code Climate reporting
  .circleci/config.yml
  package.json
Labels: enhancement

#16 exclude spec.tsx files
  tsconfig.json
Labels: enhancement, in progress

#34 Revert excluding specs in tsconfig
  tsconfig.json
Labels: enhancement

#33 Connect review component logic and presentation
  package.json
  src/App.tsx
  src/cards/CardRenderer.tsx
  src/data/Card.tsx
  src/model/Card.tsx
  src/model/interfaces.tsx
  src/review/ActionBar.spec.tsx
  src/review/ActionBar.tsx
  src/review/Review.spec.tsx
  src/review/Review.tsx
  src/review/ReviewContainer.spec.tsx
  src/review/ReviewContainer.tsx
  src/review/__snapshots__/ActionBar.spec.tsx.snap
  src/review/__snapshots__/Review.spec.tsx.snap
  src/setupTests.ts
  src/ui/Button.tsx
  yarn.lock
Labels: enhancement

#38 Clean up review code
  src/model/Card.tsx
  src/review/Review.tsx
Labels: enhancement

#39 Dumb SRS component
  package.json
  src/lib/srs/DumbSRS.spec.ts
  src/lib/srs/DumbSRS.ts
  src/lib/srs/__snapshots__/DumbSRS.spec.ts.snap
  src/lib/srs/main.ts
  yarn.lock
Labels: feature
